### ISSUE TITLE
Generated sources aren't added as source dir in non-Java projects

### ISSUE THREAD

**Issue by edeandrea** [edeandrea/xjc-generation-gradle-plugin#18]
When sources are generated (i.e. in `$buildDir/generated-sources/main/xjc`) it seems only Java-based projects can see the generated files on the classpath.

**Comment by garethpowell** [comment]
I was just about to upload a sample project to demonstrate the problem. What I also noticed was that Kotlin test sources can see the XJC generated code, but the Kotlin main sources can't.

**Comment by edeandrea** [comment]
I just published version 1.4 to the plugin portal. Can you try with that version & see if it solves your issue?

**Comment by gregorbg** [comment]
I am facing the same issue with a recent Kotlin project. The `compileKotlin` task _does_ depend on xjc code generation, but for some reason it doesn't treat the generated sources as `srcDir` unless I explicitly add it myself.

Relevant parts of the build.gradle.kts: (let me know if you need more, I'll be glad to help!)

```
plugins {
    kotlin("jvm") version "1.3.72"
    kotlin("plugin.serialization") version "1.3.72"

    id("com.github.edeandrea.xjc-generation") version "1.4"
}

dependencies {
    "xjc"("javax.xml.bind:jaxb-api:2.3.1")
    "xjc"("org.glassfish.jaxb:jaxb-runtime:2.3.1")
    "xjc"("org.glassfish.jaxb:jaxb-xjc:2.3.1")
    "xjc"("org.jvnet.jaxb2_commons:jaxb2-basics-annotate:1.1.0")
}

xjcGeneration {
    schemas {
        create("mySchema") {
            // schema by default yields files under the package "org.foo.bar"
            schemaFile = "foobar/schema.xsd"
            additionalXjcCommandLineArgs = mapOf("-Xannotate" to "")
        }
    }
}
```

Running the `build` Gradle task results in a lot of Kotlin compiler errors along the lines of `Unresolved reference: org.foo.bar.LoremIpsum` (where `LoremIpsum` is an entity defined in the xjc schema file)

Adding the following manually (!) fixes the build and makes `compileKotlin` proceed without any errors:

```
sourceSets {
    main {
        java {
            srcDir("$buildDir/generated-sources/main/xjc")
        }
    }
}
```

Interestingly, that seems to be the exact same thing that you're doing at https://github.com/edeandrea/xjc-generation-gradle-plugin/blob/master/src/main/kotlin/com/github/edeandrea/xjcplugin/plugin/XjcPlugin.kt#L102 but for some reason it doesn't propagate correctly :(

**Comment by edeandrea** [comment]
Hi @suushiemaniac Thank you for reporting this. Can I ask what Gradle version you are using?

I'll take a look at some point next week. Unfortunately I maintain this as a side project and I'm a bit swamped with my day job :(
