### ISSUE TITLE
Infer the necessary dependencies under xjc configuration

### ISSUE THREAD

**Issue by x80486** [edeandrea/xjc-generation-gradle-plugin#2]
I think it would be best if the plugin would be able to infer the required dependencies, rather than rely on the user to provide them. It's a fixed set, and allowing to change the version number (via a property/setting) it's more straightforward.

**Comment by edeandrea** [comment]
Thanks @x80486 for the interest & your comments! I'll address them all individually.

Originally I did consider inferring the required dependencies. Unfortunately I found that older jaxb versions (< 2.2.7) don't have the same set of dependencies. In JAXB up until 2.2.6 everything was in the `jaxb-impl` artifact. As of 2.2.7, it was split into a `jaxb-core` & `jaxb-impl`. Then in 2.2.10, the `org.glassfish.jaxb:jaxb-runtime` artifact was introduced.

Then if you want to be using Java 9 or greater, [you need to be using versions 2.3.x of some combination of these libraries](https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond).

This is the reason why I decided to introduce a separate configuration and allow users the ability to define the classpath that the xjc compiler runs on.

**Comment by x80486** [comment]
OK...that's all right. I really raised this one because I see that other plugins (I tested all of them :rofl:) had that capability, so if it was easy to have it, then let's ask for it :sunglasses: ...the lesser the better (in most cases).

**Comment by edeandrea** [comment]
Happy for the input. I as well have tried many of the other plugins but found none of them did exactly what I wanted, so hence this one was born :) I will admit that the overall design and structure of this one is somewhat selfish :) I mostly designed and implemented it based on how I wanted it to be used and the shortcomings I found in other ones.

I'm happy to improve this one going forward if others find it useful.

I think for this particular ticket though I'd rather leave things the way they are.
