### ISSUE TITLE
Readme should contain information about dependencies for jaxb 2.3.2

### ISSUE THREAD

**Issue by nc-ska** [edeandrea/xjc-generation-gradle-plugin#20]
It is enough to have only this dependency: `xjc "org.glassfish.jaxb:jaxb-xjc:2.3.2"`, to use this plugin, so maybe it is worth mentioning that in readme file that for jaxb version 2.3.2 it needs only this dependency.
It is likely that for jaxb 2.3.x it is working this way, but I didn't check that.

BTW Great plugin :)

**Comment by edeandrea** [comment]
Hi @nc-ska thanks for using the plugin! I've updated the README with info for JAXB 2.3.x.
