### ISSUE TITLE
"Received status code 521 from server" when trying to build my gradle project

### ISSUE THREAD

**Issue by vilimprodanovic** [edeandrea/xjc-generation-gradle-plugin#27]
Hi, I was working as usual today and suddenly, when I tried to build my gradle project, I got the following message:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project '...'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not resolve com.github.edeandrea.xjc-generation:com.github.edeandrea.xjc-generation.gradle.plugin:1.6.
>      Required by:
>          project :
>       > Could not resolve com.github.edeandrea.xjc-generation:com.github.edeandrea.xjc-generation.gradle.plugin:1.6.
>          > Could not get resource 'https://jitpack.io/com/github/edeandrea/xjc-generation/com.github.edeandrea.xjc-generation.gradle.plugin/1.6/com.github.edeandrea.xjc-generation.gradle.plugin-1.6.pom'.
>             > Could not HEAD 'https://jitpack.io/com/github/edeandrea/xjc-generation/com.github.edeandrea.xjc-generation.gradle.plugin/1.6/com.github.edeandrea.xjc-generation.gradle.plugin-1.6.pom'. Received status code 521 from server:

Is anybody having the same problem as me? Could it be the Web server for serving the plugin is not online or something like that?

I am using `mavenCentral` repository and maven repository with url `https://jitpack.io` FYI

**Comment by edeandrea** [comment]
Hi @vilimprodanovic when I google error code 521 I get

```
Error 521 occurs when the origin web server refuses connections from Cloudflare. Security solutions at your origin may block legitimate connections from certain Cloudflare IP addresses. ... Cloudflare was able to complete a TCP connection to the origin server, but did not receive a timely HTTP response.
```

It must be some kind of network error from the maven repo proxy.

**Comment by vilimprodanovic** [comment]
Yes, it was. The jitpack.io had some network problems. Now works fine
