### ISSUE TITLE
Allow modified xjc args

### ISSUE THREAD

**Issue by chrisale81** [edeandrea/xjc-generation-gradle-plugin#4]
id like to pass some args to xjc (like -Xautonaming) - this seems to be not possible. is there any chance to do that?

**Comment by edeandrea** [comment]
Thanks @chrisaie for the interest in the project! Currently this is not possible. It shouldn't be a big deal to implement though. I can most likely get to it in the next week or 2.

**Comment by edeandrea** [comment]
Hi @chrisaie this has been implemented in version 1.2 of the plugin. Any options or command line args available to the [XJC Ant Task](https://javaee.github.io/jaxb-v2/doc/user-guide/ch04.html#tools-xjc-ant-task) are now available to be customized for either all of your schemas or on a schema-by-schema basis.

See the README for details.
