### ISSUE TITLE
Unable to set generated source dir

### ISSUE THREAD

**Issue by sladflob** [edeandrea/xjc-generation-gradle-plugin#6]
Hi, I'm migrating a project from ant which uses the `-d` option on xjc to change the output directory. I have tried setting both the `additionalXjcOptions`  to include `outputdir` and `additionalXjcCommandLineArgs`  to include `-i` and neither have any effect on where the output classes go. I checked out the source and it looks like the `generatedSourcesDir` is hard-coded to `${project.buildDir}/generated-sources/$sourceSetName/xjc`. Not sure why this is? Is it possible to modify the plugin so that the output directory can be configure?

**Comment by edeandrea** [comment]
Thanks @sladflob for the note!

This project was really founded & started from my own usages of the `xjc` compiler and not finding any other plugin out there that did things exactly the way I wanted. The majority of the features are based purely on the way I did things in my own projects.

That being said, now that this is open in the open-source community I'm happy to take in other people's inputs to improve upon what is currently here. That being said - I think your use case is perfectly valid.

I'm a bit swamped this week but may have some cycles towards the end of the week or at some point next week to take a look at building this feature in, unless of course you want to issue a PR. I haven't yet put together a contribution guide (something on my "to-do" list, but whatever is built should fall into patterns/conventions already being used within the rest of the code in the project and should also make sure there are unit/integration tests proving that any commits/changes/additions work.

**Comment by sladflob** [comment]
Thanks for the reply!  I found your plugin by googling "gradle xjc plugin" and picked the one from the list that had the most recent checkin, and it seemed to be fairly intuitive to use.

There's no huge rush though having said that, we're pretty motivated about moving our project over to using Gradle at the moment so it would be good to have this feature fairly soon. I'm a fairly experience Java developer but have never used Kotlin, but I wouldn't mind giving it a go. I was thinking that maybe I could spend a day or so next week taking a look at it and see how far I get. If it seems like I can do it I will issue a PR. How does that sound to you?

**Comment by edeandrea** [comment]
Sounds like a plan to me. I wont get a chance to even look at it until the end of this week at the earliest. I'll try to get a contribution guide up by the end of the week as well.

To be honest this plugin is my first real go-around with Kotlin. I decided to build it in Kotlin instead of Groovy or Java because I wanted to learn Kotlin. I had only played with it here and there beforehand.

**Comment by sladflob** [comment]
Hi again. I checked out the sources locally and poked around and I think the changes to do this are pretty minimal. In fact I made the changes to my local copy, built it, and then pointed my Gradle script at my local jar and it seems to work. Here's what I did:

1) added a String property called 'destdir' to the Schema class. Also added a setDestDir() method that takes a file and sets the destdir property from this, just like the other properties.

2) changed the line in XjcPlugin.createTasks() where it sets generatedSourcesDir (line 79) to use Schema.desdir if it is set. So my line looks like:

`val generatedSourcesDir = schema.destdir ?: "${project.buildDir}/generated-sources/$sourceSetName/xjc"`

That is it! How does that sound to you? I'm just finding my feet with Gradle (let alone plugins) but this seems to do what I want.

**Comment by edeandrea** [comment]
Thanks @sladflob that sounds like the correct approach. You also need to modify the `Xjc` task class where it actually runs the xjc ant task.

It would be easier to review by looking at a pull request and commenting, but I think you are on the right track. I'm going to be away all day today but will be back online tomorrow. I should have a contributing guide up tomorrow as well.

You'll also need to add unit and integration tests to cover any new code being added.

**Comment by edeandrea** [comment]
Actually never mind about the Xjc class. It already handles the output directory. I think you've got it.

**Comment by pfcit** [comment]
getting the following error setting output directory
![image](https://user-images.githubusercontent.com/22390091/73376563-89678c80-42b5-11ea-9d7a-d0d19bb30e74.png)

![image](https://user-images.githubusercontent.com/22390091/73376247-fcbcce80-42b4-11ea-8166-669c7cb74e72.png)

**Comment by edeandrea** [comment]
@pfcit `generatedSourcesDir` is not a currently supported property. This ticket is to implement that feature but it has not yet been implemented. See the README.md file in the root of this repository for what is currently supported.

**Comment by edeandrea** [comment]
I've released version 1.3 to the plugin portal containing this enhancement.

**Comment by sladflob** [comment]
Thanks for this. Sorry for not doing it myself... I was using my locally modified copy and got waylaid with other stuff and never got back to it. It will be good to use the version from the portal.

**Comment by edeandrea** [comment]
No worries! Glad I could help!
