### ISSUE TITLE
Add a contributing guide

### ISSUE THREAD

**Issue by edeandrea** [edeandrea/xjc-generation-gradle-plugin#7]
Need to add a guide for contributors spelling out rules for making contributions.

**Comment by lbar** [comment]
In addition, could you provide an `.editorconfig`?

**Comment by edeandrea** [comment]
@lbar which IDEs use the `.editorconfig` file? I'm an IntelliJ user and don't see a file by that name in my local project.

**Comment by lbar** [comment]
It is just a kind of standard for basic formatting. IntelliJ natively supports this. You can see Settings > Editor > Scheme > Export.
